# Generated by Django 4.2.6 on 2023-10-09 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lesson',
            options={'ordering': ('duration',), 'verbose_name': 'Урок', 'verbose_name_plural': 'Уроки'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Продукт', 'verbose_name_plural': 'Продукты'},
        ),
        migrations.AlterModelOptions(
            name='userlesson',
            options={'verbose_name': 'Урок пользователя', 'verbose_name_plural': 'Уроки пользователей'},
        ),
        migrations.AlterModelOptions(
            name='userproducts',
            options={'verbose_name': 'Продукт пользователя', 'verbose_name_plural': 'Продукты пользователей'},
        ),
        migrations.AlterField(
            model_name='lesson',
            name='duration',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
